-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Faction_pb',package.seeall)

local TB = {}

TB.FACTIONDATA = protobuf.Descriptor();
TB.FACTIONDATA_FACTIONS_FIELD = protobuf.FieldDescriptor();
TB.BASEFACTIONTABLE = protobuf.Descriptor();
TB.BASEFACTIONTABLE_LIST_FIELD = protobuf.FieldDescriptor();

TB.FACTIONDATA_FACTIONS_FIELD.name = "factions"
TB.FACTIONDATA_FACTIONS_FIELD.full_name = ".FactionData.factions"
TB.FACTIONDATA_FACTIONS_FIELD.number = 1
TB.FACTIONDATA_FACTIONS_FIELD.index = 0
TB.FACTIONDATA_FACTIONS_FIELD.label = 3
TB.FACTIONDATA_FACTIONS_FIELD.has_default_value = false
TB.FACTIONDATA_FACTIONS_FIELD.default_value = {}
TB.FACTIONDATA_FACTIONS_FIELD.type = 5
TB.FACTIONDATA_FACTIONS_FIELD.cpp_type = 1

TB.FACTIONDATA.name = "FactionData"
TB.FACTIONDATA.full_name = ".FactionData"
TB.FACTIONDATA.nested_types = {}
TB.FACTIONDATA.enum_types = {}
TB.FACTIONDATA.fields = {TB.FACTIONDATA_FACTIONS_FIELD}
TB.FACTIONDATA.is_extendable = false
TB.FACTIONDATA.extensions = {}

TB.BASEFACTIONTABLE_LIST_FIELD.name = "list"
TB.BASEFACTIONTABLE_LIST_FIELD.full_name = ".BaseFactionTable.list"
TB.BASEFACTIONTABLE_LIST_FIELD.number = 1
TB.BASEFACTIONTABLE_LIST_FIELD.index = 0
TB.BASEFACTIONTABLE_LIST_FIELD.label = 3
TB.BASEFACTIONTABLE_LIST_FIELD.has_default_value = false
TB.BASEFACTIONTABLE_LIST_FIELD.default_value = {}
TB.BASEFACTIONTABLE_LIST_FIELD.message_type = TB.FACTIONDATA
TB.BASEFACTIONTABLE_LIST_FIELD.type = 11
TB.BASEFACTIONTABLE_LIST_FIELD.cpp_type = 10

TB.BASEFACTIONTABLE.name = "BaseFactionTable"
TB.BASEFACTIONTABLE.full_name = ".BaseFactionTable"
TB.BASEFACTIONTABLE.nested_types = {}
TB.BASEFACTIONTABLE.enum_types = {}
TB.BASEFACTIONTABLE.fields = {TB.BASEFACTIONTABLE_LIST_FIELD}
TB.BASEFACTIONTABLE.is_extendable = false
TB.BASEFACTIONTABLE.extensions = {}


BaseFactionTable = protobuf.Message(TB.BASEFACTIONTABLE)
FactionData = protobuf.Message(TB.FACTIONDATA)

