-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('IllegalData_pb',package.seeall)

local TB = {}

TB.ALLILLEGALDATA = protobuf.Descriptor();
TB.ALLILLEGALDATA_DATAS_FIELD = protobuf.FieldDescriptor();
TB.ILLEGALDATA = protobuf.Descriptor();
TB.ILLEGALDATA_ID_FIELD = protobuf.FieldDescriptor();
TB.ILLEGALDATA_STRINGVALUE_FIELD = protobuf.FieldDescriptor();

TB.ALLILLEGALDATA_DATAS_FIELD.name = "datas"
TB.ALLILLEGALDATA_DATAS_FIELD.full_name = ".AllIllegalData.datas"
TB.ALLILLEGALDATA_DATAS_FIELD.number = 1
TB.ALLILLEGALDATA_DATAS_FIELD.index = 0
TB.ALLILLEGALDATA_DATAS_FIELD.label = 3
TB.ALLILLEGALDATA_DATAS_FIELD.has_default_value = false
TB.ALLILLEGALDATA_DATAS_FIELD.default_value = {}
TB.ALLILLEGALDATA_DATAS_FIELD.message_type = TB.ILLEGALDATA
TB.ALLILLEGALDATA_DATAS_FIELD.type = 11
TB.ALLILLEGALDATA_DATAS_FIELD.cpp_type = 10

TB.ALLILLEGALDATA.name = "AllIllegalData"
TB.ALLILLEGALDATA.full_name = ".AllIllegalData"
TB.ALLILLEGALDATA.nested_types = {}
TB.ALLILLEGALDATA.enum_types = {}
TB.ALLILLEGALDATA.fields = {TB.ALLILLEGALDATA_DATAS_FIELD}
TB.ALLILLEGALDATA.is_extendable = false
TB.ALLILLEGALDATA.extensions = {}

TB.ILLEGALDATA_ID_FIELD.name = "id"
TB.ILLEGALDATA_ID_FIELD.full_name = ".IllegalData.id"
TB.ILLEGALDATA_ID_FIELD.number = 1
TB.ILLEGALDATA_ID_FIELD.index = 0
TB.ILLEGALDATA_ID_FIELD.label = 1
TB.ILLEGALDATA_ID_FIELD.has_default_value = false
TB.ILLEGALDATA_ID_FIELD.default_value = ""
TB.ILLEGALDATA_ID_FIELD.type = 9
TB.ILLEGALDATA_ID_FIELD.cpp_type = 9

TB.ILLEGALDATA_STRINGVALUE_FIELD.name = "stringValue"
TB.ILLEGALDATA_STRINGVALUE_FIELD.full_name = ".IllegalData.stringValue"
TB.ILLEGALDATA_STRINGVALUE_FIELD.number = 2
TB.ILLEGALDATA_STRINGVALUE_FIELD.index = 1
TB.ILLEGALDATA_STRINGVALUE_FIELD.label = 1
TB.ILLEGALDATA_STRINGVALUE_FIELD.has_default_value = false
TB.ILLEGALDATA_STRINGVALUE_FIELD.default_value = ""
TB.ILLEGALDATA_STRINGVALUE_FIELD.type = 9
TB.ILLEGALDATA_STRINGVALUE_FIELD.cpp_type = 9

TB.ILLEGALDATA.name = "IllegalData"
TB.ILLEGALDATA.full_name = ".IllegalData"
TB.ILLEGALDATA.nested_types = {}
TB.ILLEGALDATA.enum_types = {}
TB.ILLEGALDATA.fields = {TB.ILLEGALDATA_ID_FIELD, TB.ILLEGALDATA_STRINGVALUE_FIELD}
TB.ILLEGALDATA.is_extendable = false
TB.ILLEGALDATA.extensions = {}


AllIllegalData = protobuf.Message(TB.ALLILLEGALDATA)
IllegalData = protobuf.Message(TB.ILLEGALDATA)

