-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('LoadingInfo_pb',package.seeall)

local TB = {}

TB.TIP = protobuf.Descriptor();
TB.TIP_ID_FIELD = protobuf.FieldDescriptor();
TB.TIP_CONTEXTTYPE_FIELD = protobuf.FieldDescriptor();
TB.TIP_CONTEXTVALUE_FIELD = protobuf.FieldDescriptor();
TB.TIPLIST = protobuf.Descriptor();
TB.TIPLIST_TIPS_FIELD = protobuf.FieldDescriptor();
TB.BGINFO = protobuf.Descriptor();
TB.BGINFO_BGTYPE = protobuf.EnumDescriptor();
TB.BGINFO_BGTYPE_IMAGE_ENUM = protobuf.EnumValueDescriptor();
TB.BGINFO_BGTYPE_SPINE_ENUM = protobuf.EnumValueDescriptor();
TB.BGINFO_ID_FIELD = protobuf.FieldDescriptor();
TB.BGINFO_SCENENAME_FIELD = protobuf.FieldDescriptor();
TB.BGINFO_SCENETYPE_FIELD = protobuf.FieldDescriptor();
TB.BGINFO_BGTYPE_FIELD = protobuf.FieldDescriptor();
TB.BGINFO_RESNAME_FIELD = protobuf.FieldDescriptor();
TB.BGLIST = protobuf.Descriptor();
TB.BGLIST_INFOS_FIELD = protobuf.FieldDescriptor();

TB.TIP_ID_FIELD.name = "id"
TB.TIP_ID_FIELD.full_name = ".Tip.id"
TB.TIP_ID_FIELD.number = 1
TB.TIP_ID_FIELD.index = 0
TB.TIP_ID_FIELD.label = 1
TB.TIP_ID_FIELD.has_default_value = false
TB.TIP_ID_FIELD.default_value = ""
TB.TIP_ID_FIELD.type = 9
TB.TIP_ID_FIELD.cpp_type = 9

TB.TIP_CONTEXTTYPE_FIELD.name = "contextType"
TB.TIP_CONTEXTTYPE_FIELD.full_name = ".Tip.contextType"
TB.TIP_CONTEXTTYPE_FIELD.number = 2
TB.TIP_CONTEXTTYPE_FIELD.index = 1
TB.TIP_CONTEXTTYPE_FIELD.label = 1
TB.TIP_CONTEXTTYPE_FIELD.has_default_value = false
TB.TIP_CONTEXTTYPE_FIELD.default_value = 0
TB.TIP_CONTEXTTYPE_FIELD.type = 5
TB.TIP_CONTEXTTYPE_FIELD.cpp_type = 1

TB.TIP_CONTEXTVALUE_FIELD.name = "contextValue"
TB.TIP_CONTEXTVALUE_FIELD.full_name = ".Tip.contextValue"
TB.TIP_CONTEXTVALUE_FIELD.number = 3
TB.TIP_CONTEXTVALUE_FIELD.index = 2
TB.TIP_CONTEXTVALUE_FIELD.label = 1
TB.TIP_CONTEXTVALUE_FIELD.has_default_value = false
TB.TIP_CONTEXTVALUE_FIELD.default_value = ""
TB.TIP_CONTEXTVALUE_FIELD.type = 9
TB.TIP_CONTEXTVALUE_FIELD.cpp_type = 9

TB.TIP.name = "Tip"
TB.TIP.full_name = ".Tip"
TB.TIP.nested_types = {}
TB.TIP.enum_types = {}
TB.TIP.fields = {TB.TIP_ID_FIELD, TB.TIP_CONTEXTTYPE_FIELD, TB.TIP_CONTEXTVALUE_FIELD}
TB.TIP.is_extendable = false
TB.TIP.extensions = {}

TB.TIPLIST_TIPS_FIELD.name = "Tips"
TB.TIPLIST_TIPS_FIELD.full_name = ".TipList.Tips"
TB.TIPLIST_TIPS_FIELD.number = 1
TB.TIPLIST_TIPS_FIELD.index = 0
TB.TIPLIST_TIPS_FIELD.label = 3
TB.TIPLIST_TIPS_FIELD.has_default_value = false
TB.TIPLIST_TIPS_FIELD.default_value = {}
TB.TIPLIST_TIPS_FIELD.message_type = TB.TIP
TB.TIPLIST_TIPS_FIELD.type = 11
TB.TIPLIST_TIPS_FIELD.cpp_type = 10

TB.TIPLIST.name = "TipList"
TB.TIPLIST.full_name = ".TipList"
TB.TIPLIST.nested_types = {}
TB.TIPLIST.enum_types = {}
TB.TIPLIST.fields = {TB.TIPLIST_TIPS_FIELD}
TB.TIPLIST.is_extendable = false
TB.TIPLIST.extensions = {}

TB.BGINFO_BGTYPE_IMAGE_ENUM.name = "IMAGE"
TB.BGINFO_BGTYPE_IMAGE_ENUM.index = 0
TB.BGINFO_BGTYPE_IMAGE_ENUM.number = 0
TB.BGINFO_BGTYPE_SPINE_ENUM.name = "SPINE"
TB.BGINFO_BGTYPE_SPINE_ENUM.index = 1
TB.BGINFO_BGTYPE_SPINE_ENUM.number = 1
TB.BGINFO_BGTYPE.name = "BgType"
TB.BGINFO_BGTYPE.full_name = ".BgInfo.BgType"
TB.BGINFO_BGTYPE.values = {TB.BGINFO_BGTYPE_IMAGE_ENUM,TB.BGINFO_BGTYPE_SPINE_ENUM}
TB.BGINFO_ID_FIELD.name = "id"
TB.BGINFO_ID_FIELD.full_name = ".BgInfo.id"
TB.BGINFO_ID_FIELD.number = 1
TB.BGINFO_ID_FIELD.index = 0
TB.BGINFO_ID_FIELD.label = 1
TB.BGINFO_ID_FIELD.has_default_value = false
TB.BGINFO_ID_FIELD.default_value = ""
TB.BGINFO_ID_FIELD.type = 9
TB.BGINFO_ID_FIELD.cpp_type = 9

TB.BGINFO_SCENENAME_FIELD.name = "sceneName"
TB.BGINFO_SCENENAME_FIELD.full_name = ".BgInfo.sceneName"
TB.BGINFO_SCENENAME_FIELD.number = 2
TB.BGINFO_SCENENAME_FIELD.index = 1
TB.BGINFO_SCENENAME_FIELD.label = 1
TB.BGINFO_SCENENAME_FIELD.has_default_value = false
TB.BGINFO_SCENENAME_FIELD.default_value = ""
TB.BGINFO_SCENENAME_FIELD.type = 9
TB.BGINFO_SCENENAME_FIELD.cpp_type = 9

TB.BGINFO_SCENETYPE_FIELD.name = "sceneType"
TB.BGINFO_SCENETYPE_FIELD.full_name = ".BgInfo.sceneType"
TB.BGINFO_SCENETYPE_FIELD.number = 3
TB.BGINFO_SCENETYPE_FIELD.index = 2
TB.BGINFO_SCENETYPE_FIELD.label = 1
TB.BGINFO_SCENETYPE_FIELD.has_default_value = false
TB.BGINFO_SCENETYPE_FIELD.default_value = 0
TB.BGINFO_SCENETYPE_FIELD.type = 5
TB.BGINFO_SCENETYPE_FIELD.cpp_type = 1

TB.BGINFO_BGTYPE_FIELD.name = "bgType"
TB.BGINFO_BGTYPE_FIELD.full_name = ".BgInfo.bgType"
TB.BGINFO_BGTYPE_FIELD.number = 4
TB.BGINFO_BGTYPE_FIELD.index = 3
TB.BGINFO_BGTYPE_FIELD.label = 1
TB.BGINFO_BGTYPE_FIELD.has_default_value = false
TB.BGINFO_BGTYPE_FIELD.default_value = 0
TB.BGINFO_BGTYPE_FIELD.enum_type = TB.BGINFO_BGTYPE
TB.BGINFO_BGTYPE_FIELD.type = 14
TB.BGINFO_BGTYPE_FIELD.cpp_type = 8

TB.BGINFO_RESNAME_FIELD.name = "resName"
TB.BGINFO_RESNAME_FIELD.full_name = ".BgInfo.resName"
TB.BGINFO_RESNAME_FIELD.number = 5
TB.BGINFO_RESNAME_FIELD.index = 4
TB.BGINFO_RESNAME_FIELD.label = 1
TB.BGINFO_RESNAME_FIELD.has_default_value = false
TB.BGINFO_RESNAME_FIELD.default_value = ""
TB.BGINFO_RESNAME_FIELD.type = 9
TB.BGINFO_RESNAME_FIELD.cpp_type = 9

TB.BGINFO.name = "BgInfo"
TB.BGINFO.full_name = ".BgInfo"
TB.BGINFO.nested_types = {}
TB.BGINFO.enum_types = {TB.BGINFO_BGTYPE}
TB.BGINFO.fields = {TB.BGINFO_ID_FIELD, TB.BGINFO_SCENENAME_FIELD, TB.BGINFO_SCENETYPE_FIELD, TB.BGINFO_BGTYPE_FIELD, TB.BGINFO_RESNAME_FIELD}
TB.BGINFO.is_extendable = false
TB.BGINFO.extensions = {}

TB.BGLIST_INFOS_FIELD.name = "infos"
TB.BGLIST_INFOS_FIELD.full_name = ".BgList.infos"
TB.BGLIST_INFOS_FIELD.number = 1
TB.BGLIST_INFOS_FIELD.index = 0
TB.BGLIST_INFOS_FIELD.label = 3
TB.BGLIST_INFOS_FIELD.has_default_value = false
TB.BGLIST_INFOS_FIELD.default_value = {}
TB.BGLIST_INFOS_FIELD.message_type = TB.BGINFO
TB.BGLIST_INFOS_FIELD.type = 11
TB.BGLIST_INFOS_FIELD.cpp_type = 10

TB.BGLIST.name = "BgList"
TB.BGLIST.full_name = ".BgList"
TB.BGLIST.nested_types = {}
TB.BGLIST.enum_types = {}
TB.BGLIST.fields = {TB.BGLIST_INFOS_FIELD}
TB.BGLIST.is_extendable = false
TB.BGLIST.extensions = {}


BgInfo = protobuf.Message(TB.BGINFO)
BgList = protobuf.Message(TB.BGLIST)
Tip = protobuf.Message(TB.TIP)
TipList = protobuf.Message(TB.TIPLIST)

