-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Mail_pb',package.seeall)

local TB = {}

TB.MAILTYPE = protobuf.EnumDescriptor();
TB.MAILTYPE_MAILTYPE_SYSTEM_ENUM = protobuf.EnumValueDescriptor();
TB.MAILITEM = protobuf.Descriptor();
TB.MAILITEM_ITEMID_FIELD = protobuf.FieldDescriptor();
TB.MAILITEM_COUNT_FIELD = protobuf.FieldDescriptor();
TB.MAILTEXT = protobuf.Descriptor();
TB.MAILTEXT_FROM_FIELD = protobuf.FieldDescriptor();
TB.MAILTEXT_TITLE_FIELD = protobuf.FieldDescriptor();
TB.MAILTEXT_TEXT_FIELD = protobuf.FieldDescriptor();
TB.MAILATTACH = protobuf.Descriptor();
TB.MAILATTACH_ITEMLIST_FIELD = protobuf.FieldDescriptor();
TB.MAILCONTENT = protobuf.Descriptor();
TB.MAILCONTENT_TXT_FIELD = protobuf.FieldDescriptor();
TB.MAILCONTENT_ATTACH_FIELD = protobuf.FieldDescriptor();
TB.MAILLIST = protobuf.Descriptor();
TB.MAILLIST_ID_FIELD = protobuf.FieldDescriptor();
TB.MAILLIST_TITLE_FIELD = protobuf.FieldDescriptor();
TB.MAILLIST_TEXT_FIELD = protobuf.FieldDescriptor();
TB.MAILLIST_SENDER_FIELD = protobuf.FieldDescriptor();
TB.MAILLIST_ATTACH_FIELD = protobuf.FieldDescriptor();
TB.ALLMAILLIST = protobuf.Descriptor();
TB.ALLMAILLIST_LIST_FIELD = protobuf.FieldDescriptor();

TB.MAILTYPE_MAILTYPE_SYSTEM_ENUM.name = "MailType_System"
TB.MAILTYPE_MAILTYPE_SYSTEM_ENUM.index = 0
TB.MAILTYPE_MAILTYPE_SYSTEM_ENUM.number = 2
TB.MAILTYPE.name = "MailType"
TB.MAILTYPE.full_name = ".MailType"
TB.MAILTYPE.values = {TB.MAILTYPE_MAILTYPE_SYSTEM_ENUM}
TB.MAILITEM_ITEMID_FIELD.name = "itemid"
TB.MAILITEM_ITEMID_FIELD.full_name = ".MailItem.itemid"
TB.MAILITEM_ITEMID_FIELD.number = 1
TB.MAILITEM_ITEMID_FIELD.index = 0
TB.MAILITEM_ITEMID_FIELD.label = 1
TB.MAILITEM_ITEMID_FIELD.has_default_value = false
TB.MAILITEM_ITEMID_FIELD.default_value = 0
TB.MAILITEM_ITEMID_FIELD.type = 5
TB.MAILITEM_ITEMID_FIELD.cpp_type = 1

TB.MAILITEM_COUNT_FIELD.name = "count"
TB.MAILITEM_COUNT_FIELD.full_name = ".MailItem.count"
TB.MAILITEM_COUNT_FIELD.number = 2
TB.MAILITEM_COUNT_FIELD.index = 1
TB.MAILITEM_COUNT_FIELD.label = 1
TB.MAILITEM_COUNT_FIELD.has_default_value = false
TB.MAILITEM_COUNT_FIELD.default_value = 0
TB.MAILITEM_COUNT_FIELD.type = 5
TB.MAILITEM_COUNT_FIELD.cpp_type = 1

TB.MAILITEM.name = "MailItem"
TB.MAILITEM.full_name = ".MailItem"
TB.MAILITEM.nested_types = {}
TB.MAILITEM.enum_types = {}
TB.MAILITEM.fields = {TB.MAILITEM_ITEMID_FIELD, TB.MAILITEM_COUNT_FIELD}
TB.MAILITEM.is_extendable = false
TB.MAILITEM.extensions = {}

TB.MAILTEXT_FROM_FIELD.name = "from"
TB.MAILTEXT_FROM_FIELD.full_name = ".MailText.from"
TB.MAILTEXT_FROM_FIELD.number = 1
TB.MAILTEXT_FROM_FIELD.index = 0
TB.MAILTEXT_FROM_FIELD.label = 1
TB.MAILTEXT_FROM_FIELD.has_default_value = false
TB.MAILTEXT_FROM_FIELD.default_value = ""
TB.MAILTEXT_FROM_FIELD.type = 9
TB.MAILTEXT_FROM_FIELD.cpp_type = 9

TB.MAILTEXT_TITLE_FIELD.name = "title"
TB.MAILTEXT_TITLE_FIELD.full_name = ".MailText.title"
TB.MAILTEXT_TITLE_FIELD.number = 2
TB.MAILTEXT_TITLE_FIELD.index = 1
TB.MAILTEXT_TITLE_FIELD.label = 1
TB.MAILTEXT_TITLE_FIELD.has_default_value = false
TB.MAILTEXT_TITLE_FIELD.default_value = ""
TB.MAILTEXT_TITLE_FIELD.type = 9
TB.MAILTEXT_TITLE_FIELD.cpp_type = 9

TB.MAILTEXT_TEXT_FIELD.name = "text"
TB.MAILTEXT_TEXT_FIELD.full_name = ".MailText.text"
TB.MAILTEXT_TEXT_FIELD.number = 3
TB.MAILTEXT_TEXT_FIELD.index = 2
TB.MAILTEXT_TEXT_FIELD.label = 1
TB.MAILTEXT_TEXT_FIELD.has_default_value = false
TB.MAILTEXT_TEXT_FIELD.default_value = ""
TB.MAILTEXT_TEXT_FIELD.type = 9
TB.MAILTEXT_TEXT_FIELD.cpp_type = 9

TB.MAILTEXT.name = "MailText"
TB.MAILTEXT.full_name = ".MailText"
TB.MAILTEXT.nested_types = {}
TB.MAILTEXT.enum_types = {}
TB.MAILTEXT.fields = {TB.MAILTEXT_FROM_FIELD, TB.MAILTEXT_TITLE_FIELD, TB.MAILTEXT_TEXT_FIELD}
TB.MAILTEXT.is_extendable = false
TB.MAILTEXT.extensions = {}

TB.MAILATTACH_ITEMLIST_FIELD.name = "itemlist"
TB.MAILATTACH_ITEMLIST_FIELD.full_name = ".MailAttach.itemlist"
TB.MAILATTACH_ITEMLIST_FIELD.number = 1
TB.MAILATTACH_ITEMLIST_FIELD.index = 0
TB.MAILATTACH_ITEMLIST_FIELD.label = 3
TB.MAILATTACH_ITEMLIST_FIELD.has_default_value = false
TB.MAILATTACH_ITEMLIST_FIELD.default_value = {}
TB.MAILATTACH_ITEMLIST_FIELD.message_type = TB.MAILITEM
TB.MAILATTACH_ITEMLIST_FIELD.type = 11
TB.MAILATTACH_ITEMLIST_FIELD.cpp_type = 10

TB.MAILATTACH.name = "MailAttach"
TB.MAILATTACH.full_name = ".MailAttach"
TB.MAILATTACH.nested_types = {}
TB.MAILATTACH.enum_types = {}
TB.MAILATTACH.fields = {TB.MAILATTACH_ITEMLIST_FIELD}
TB.MAILATTACH.is_extendable = false
TB.MAILATTACH.extensions = {}

TB.MAILCONTENT_TXT_FIELD.name = "txt"
TB.MAILCONTENT_TXT_FIELD.full_name = ".MailConTent.txt"
TB.MAILCONTENT_TXT_FIELD.number = 1
TB.MAILCONTENT_TXT_FIELD.index = 0
TB.MAILCONTENT_TXT_FIELD.label = 1
TB.MAILCONTENT_TXT_FIELD.has_default_value = false
TB.MAILCONTENT_TXT_FIELD.default_value = nil
TB.MAILCONTENT_TXT_FIELD.message_type = TB.MAILTEXT
TB.MAILCONTENT_TXT_FIELD.type = 11
TB.MAILCONTENT_TXT_FIELD.cpp_type = 10

TB.MAILCONTENT_ATTACH_FIELD.name = "attach"
TB.MAILCONTENT_ATTACH_FIELD.full_name = ".MailConTent.attach"
TB.MAILCONTENT_ATTACH_FIELD.number = 2
TB.MAILCONTENT_ATTACH_FIELD.index = 1
TB.MAILCONTENT_ATTACH_FIELD.label = 1
TB.MAILCONTENT_ATTACH_FIELD.has_default_value = false
TB.MAILCONTENT_ATTACH_FIELD.default_value = nil
TB.MAILCONTENT_ATTACH_FIELD.message_type = TB.MAILATTACH
TB.MAILCONTENT_ATTACH_FIELD.type = 11
TB.MAILCONTENT_ATTACH_FIELD.cpp_type = 10

TB.MAILCONTENT.name = "MailConTent"
TB.MAILCONTENT.full_name = ".MailConTent"
TB.MAILCONTENT.nested_types = {}
TB.MAILCONTENT.enum_types = {}
TB.MAILCONTENT.fields = {TB.MAILCONTENT_TXT_FIELD, TB.MAILCONTENT_ATTACH_FIELD}
TB.MAILCONTENT.is_extendable = false
TB.MAILCONTENT.extensions = {}

TB.MAILLIST_ID_FIELD.name = "id"
TB.MAILLIST_ID_FIELD.full_name = ".MailList.id"
TB.MAILLIST_ID_FIELD.number = 1
TB.MAILLIST_ID_FIELD.index = 0
TB.MAILLIST_ID_FIELD.label = 1
TB.MAILLIST_ID_FIELD.has_default_value = false
TB.MAILLIST_ID_FIELD.default_value = 0
TB.MAILLIST_ID_FIELD.type = 5
TB.MAILLIST_ID_FIELD.cpp_type = 1

TB.MAILLIST_TITLE_FIELD.name = "title"
TB.MAILLIST_TITLE_FIELD.full_name = ".MailList.title"
TB.MAILLIST_TITLE_FIELD.number = 2
TB.MAILLIST_TITLE_FIELD.index = 1
TB.MAILLIST_TITLE_FIELD.label = 1
TB.MAILLIST_TITLE_FIELD.has_default_value = false
TB.MAILLIST_TITLE_FIELD.default_value = ""
TB.MAILLIST_TITLE_FIELD.type = 9
TB.MAILLIST_TITLE_FIELD.cpp_type = 9

TB.MAILLIST_TEXT_FIELD.name = "text"
TB.MAILLIST_TEXT_FIELD.full_name = ".MailList.text"
TB.MAILLIST_TEXT_FIELD.number = 3
TB.MAILLIST_TEXT_FIELD.index = 2
TB.MAILLIST_TEXT_FIELD.label = 1
TB.MAILLIST_TEXT_FIELD.has_default_value = false
TB.MAILLIST_TEXT_FIELD.default_value = ""
TB.MAILLIST_TEXT_FIELD.type = 9
TB.MAILLIST_TEXT_FIELD.cpp_type = 9

TB.MAILLIST_SENDER_FIELD.name = "sender"
TB.MAILLIST_SENDER_FIELD.full_name = ".MailList.sender"
TB.MAILLIST_SENDER_FIELD.number = 4
TB.MAILLIST_SENDER_FIELD.index = 3
TB.MAILLIST_SENDER_FIELD.label = 1
TB.MAILLIST_SENDER_FIELD.has_default_value = false
TB.MAILLIST_SENDER_FIELD.default_value = ""
TB.MAILLIST_SENDER_FIELD.type = 9
TB.MAILLIST_SENDER_FIELD.cpp_type = 9

TB.MAILLIST_ATTACH_FIELD.name = "attach"
TB.MAILLIST_ATTACH_FIELD.full_name = ".MailList.attach"
TB.MAILLIST_ATTACH_FIELD.number = 5
TB.MAILLIST_ATTACH_FIELD.index = 4
TB.MAILLIST_ATTACH_FIELD.label = 3
TB.MAILLIST_ATTACH_FIELD.has_default_value = false
TB.MAILLIST_ATTACH_FIELD.default_value = {}
TB.MAILLIST_ATTACH_FIELD.message_type = TB.MAILITEM
TB.MAILLIST_ATTACH_FIELD.type = 11
TB.MAILLIST_ATTACH_FIELD.cpp_type = 10

TB.MAILLIST.name = "MailList"
TB.MAILLIST.full_name = ".MailList"
TB.MAILLIST.nested_types = {}
TB.MAILLIST.enum_types = {}
TB.MAILLIST.fields = {TB.MAILLIST_ID_FIELD, TB.MAILLIST_TITLE_FIELD, TB.MAILLIST_TEXT_FIELD, TB.MAILLIST_SENDER_FIELD, TB.MAILLIST_ATTACH_FIELD}
TB.MAILLIST.is_extendable = false
TB.MAILLIST.extensions = {}

TB.ALLMAILLIST_LIST_FIELD.name = "list"
TB.ALLMAILLIST_LIST_FIELD.full_name = ".AllMailList.list"
TB.ALLMAILLIST_LIST_FIELD.number = 1
TB.ALLMAILLIST_LIST_FIELD.index = 0
TB.ALLMAILLIST_LIST_FIELD.label = 3
TB.ALLMAILLIST_LIST_FIELD.has_default_value = false
TB.ALLMAILLIST_LIST_FIELD.default_value = {}
TB.ALLMAILLIST_LIST_FIELD.message_type = TB.MAILLIST
TB.ALLMAILLIST_LIST_FIELD.type = 11
TB.ALLMAILLIST_LIST_FIELD.cpp_type = 10

TB.ALLMAILLIST.name = "AllMailList"
TB.ALLMAILLIST.full_name = ".AllMailList"
TB.ALLMAILLIST.nested_types = {}
TB.ALLMAILLIST.enum_types = {}
TB.ALLMAILLIST.fields = {TB.ALLMAILLIST_LIST_FIELD}
TB.ALLMAILLIST.is_extendable = false
TB.ALLMAILLIST.extensions = {}


AllMailList = protobuf.Message(TB.ALLMAILLIST)
MailAttach = protobuf.Message(TB.MAILATTACH)
MailConTent = protobuf.Message(TB.MAILCONTENT)
MailItem = protobuf.Message(TB.MAILITEM)
MailList = protobuf.Message(TB.MAILLIST)
MailText = protobuf.Message(TB.MAILTEXT)
MailType_System = 2

