-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Physique_pb',package.seeall)

local TB = {}

TB.PHYSIQUE = protobuf.Descriptor();
TB.PHYSIQUE_ID_FIELD = protobuf.FieldDescriptor();
TB.PHYSIQUE_BONEID_FIELD = protobuf.FieldDescriptor();
TB.PHYSIQUE_CONTROLLERID_FIELD = protobuf.FieldDescriptor();
TB.PHYSIQUE_BODYIDS_FIELD = protobuf.FieldDescriptor();
TB.PHYSIQUE_RENDERID_FIELD = protobuf.FieldDescriptor();
TB.ALLPHYSIQUES = protobuf.Descriptor();
TB.ALLPHYSIQUES_DATAS_FIELD = protobuf.FieldDescriptor();

TB.PHYSIQUE_ID_FIELD.name = "id"
TB.PHYSIQUE_ID_FIELD.full_name = ".Physique.id"
TB.PHYSIQUE_ID_FIELD.number = 1
TB.PHYSIQUE_ID_FIELD.index = 0
TB.PHYSIQUE_ID_FIELD.label = 1
TB.PHYSIQUE_ID_FIELD.has_default_value = false
TB.PHYSIQUE_ID_FIELD.default_value = 0
TB.PHYSIQUE_ID_FIELD.type = 5
TB.PHYSIQUE_ID_FIELD.cpp_type = 1

TB.PHYSIQUE_BONEID_FIELD.name = "boneID"
TB.PHYSIQUE_BONEID_FIELD.full_name = ".Physique.boneID"
TB.PHYSIQUE_BONEID_FIELD.number = 2
TB.PHYSIQUE_BONEID_FIELD.index = 1
TB.PHYSIQUE_BONEID_FIELD.label = 1
TB.PHYSIQUE_BONEID_FIELD.has_default_value = false
TB.PHYSIQUE_BONEID_FIELD.default_value = 0
TB.PHYSIQUE_BONEID_FIELD.type = 5
TB.PHYSIQUE_BONEID_FIELD.cpp_type = 1

TB.PHYSIQUE_CONTROLLERID_FIELD.name = "controllerID"
TB.PHYSIQUE_CONTROLLERID_FIELD.full_name = ".Physique.controllerID"
TB.PHYSIQUE_CONTROLLERID_FIELD.number = 3
TB.PHYSIQUE_CONTROLLERID_FIELD.index = 2
TB.PHYSIQUE_CONTROLLERID_FIELD.label = 1
TB.PHYSIQUE_CONTROLLERID_FIELD.has_default_value = false
TB.PHYSIQUE_CONTROLLERID_FIELD.default_value = 0
TB.PHYSIQUE_CONTROLLERID_FIELD.type = 5
TB.PHYSIQUE_CONTROLLERID_FIELD.cpp_type = 1

TB.PHYSIQUE_BODYIDS_FIELD.name = "bodyIDs"
TB.PHYSIQUE_BODYIDS_FIELD.full_name = ".Physique.bodyIDs"
TB.PHYSIQUE_BODYIDS_FIELD.number = 4
TB.PHYSIQUE_BODYIDS_FIELD.index = 3
TB.PHYSIQUE_BODYIDS_FIELD.label = 3
TB.PHYSIQUE_BODYIDS_FIELD.has_default_value = false
TB.PHYSIQUE_BODYIDS_FIELD.default_value = {}
TB.PHYSIQUE_BODYIDS_FIELD.type = 5
TB.PHYSIQUE_BODYIDS_FIELD.cpp_type = 1

TB.PHYSIQUE_RENDERID_FIELD.name = "renderID"
TB.PHYSIQUE_RENDERID_FIELD.full_name = ".Physique.renderID"
TB.PHYSIQUE_RENDERID_FIELD.number = 5
TB.PHYSIQUE_RENDERID_FIELD.index = 4
TB.PHYSIQUE_RENDERID_FIELD.label = 1
TB.PHYSIQUE_RENDERID_FIELD.has_default_value = false
TB.PHYSIQUE_RENDERID_FIELD.default_value = 0
TB.PHYSIQUE_RENDERID_FIELD.type = 5
TB.PHYSIQUE_RENDERID_FIELD.cpp_type = 1

TB.PHYSIQUE.name = "Physique"
TB.PHYSIQUE.full_name = ".Physique"
TB.PHYSIQUE.nested_types = {}
TB.PHYSIQUE.enum_types = {}
TB.PHYSIQUE.fields = {TB.PHYSIQUE_ID_FIELD, TB.PHYSIQUE_BONEID_FIELD, TB.PHYSIQUE_CONTROLLERID_FIELD, TB.PHYSIQUE_BODYIDS_FIELD, TB.PHYSIQUE_RENDERID_FIELD}
TB.PHYSIQUE.is_extendable = false
TB.PHYSIQUE.extensions = {}

TB.ALLPHYSIQUES_DATAS_FIELD.name = "datas"
TB.ALLPHYSIQUES_DATAS_FIELD.full_name = ".AllPhysiques.datas"
TB.ALLPHYSIQUES_DATAS_FIELD.number = 1
TB.ALLPHYSIQUES_DATAS_FIELD.index = 0
TB.ALLPHYSIQUES_DATAS_FIELD.label = 3
TB.ALLPHYSIQUES_DATAS_FIELD.has_default_value = false
TB.ALLPHYSIQUES_DATAS_FIELD.default_value = {}
TB.ALLPHYSIQUES_DATAS_FIELD.message_type = TB.PHYSIQUE
TB.ALLPHYSIQUES_DATAS_FIELD.type = 11
TB.ALLPHYSIQUES_DATAS_FIELD.cpp_type = 10

TB.ALLPHYSIQUES.name = "AllPhysiques"
TB.ALLPHYSIQUES.full_name = ".AllPhysiques"
TB.ALLPHYSIQUES.nested_types = {}
TB.ALLPHYSIQUES.enum_types = {}
TB.ALLPHYSIQUES.fields = {TB.ALLPHYSIQUES_DATAS_FIELD}
TB.ALLPHYSIQUES.is_extendable = false
TB.ALLPHYSIQUES.extensions = {}


AllPhysiques = protobuf.Message(TB.ALLPHYSIQUES)
Physique = protobuf.Message(TB.PHYSIQUE)

