-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('ResConfig_pb',package.seeall)

local TB = {}

TB.RESCONFIG = protobuf.Descriptor();
TB.RESCONFIG_ID_FIELD = protobuf.FieldDescriptor();
TB.RESCONFIG_NAME_FIELD = protobuf.FieldDescriptor();
TB.RESCONFIG_PATH_FIELD = protobuf.FieldDescriptor();
TB.ALLRESCONFIG = protobuf.Descriptor();
TB.ALLRESCONFIG_DATAS_FIELD = protobuf.FieldDescriptor();
TB.BYTESCONFIG = protobuf.Descriptor();
TB.BYTESCONFIG_OFFSET_FIELD = protobuf.FieldDescriptor();
TB.BYTESCONFIG_LENGTH_FIELD = protobuf.FieldDescriptor();
TB.BYTESCONFIG_NAME_FIELD = protobuf.FieldDescriptor();
TB.ALLBYTESCONFIG = protobuf.Descriptor();
TB.ALLBYTESCONFIG_DATAS_FIELD = protobuf.FieldDescriptor();

TB.RESCONFIG_ID_FIELD.name = "id"
TB.RESCONFIG_ID_FIELD.full_name = ".ResConfig.id"
TB.RESCONFIG_ID_FIELD.number = 1
TB.RESCONFIG_ID_FIELD.index = 0
TB.RESCONFIG_ID_FIELD.label = 1
TB.RESCONFIG_ID_FIELD.has_default_value = false
TB.RESCONFIG_ID_FIELD.default_value = 0
TB.RESCONFIG_ID_FIELD.type = 5
TB.RESCONFIG_ID_FIELD.cpp_type = 1

TB.RESCONFIG_NAME_FIELD.name = "name"
TB.RESCONFIG_NAME_FIELD.full_name = ".ResConfig.name"
TB.RESCONFIG_NAME_FIELD.number = 2
TB.RESCONFIG_NAME_FIELD.index = 1
TB.RESCONFIG_NAME_FIELD.label = 1
TB.RESCONFIG_NAME_FIELD.has_default_value = false
TB.RESCONFIG_NAME_FIELD.default_value = ""
TB.RESCONFIG_NAME_FIELD.type = 9
TB.RESCONFIG_NAME_FIELD.cpp_type = 9

TB.RESCONFIG_PATH_FIELD.name = "path"
TB.RESCONFIG_PATH_FIELD.full_name = ".ResConfig.path"
TB.RESCONFIG_PATH_FIELD.number = 3
TB.RESCONFIG_PATH_FIELD.index = 2
TB.RESCONFIG_PATH_FIELD.label = 1
TB.RESCONFIG_PATH_FIELD.has_default_value = false
TB.RESCONFIG_PATH_FIELD.default_value = ""
TB.RESCONFIG_PATH_FIELD.type = 9
TB.RESCONFIG_PATH_FIELD.cpp_type = 9

TB.RESCONFIG.name = "ResConfig"
TB.RESCONFIG.full_name = ".ResConfig"
TB.RESCONFIG.nested_types = {}
TB.RESCONFIG.enum_types = {}
TB.RESCONFIG.fields = {TB.RESCONFIG_ID_FIELD, TB.RESCONFIG_NAME_FIELD, TB.RESCONFIG_PATH_FIELD}
TB.RESCONFIG.is_extendable = false
TB.RESCONFIG.extensions = {}

TB.ALLRESCONFIG_DATAS_FIELD.name = "datas"
TB.ALLRESCONFIG_DATAS_FIELD.full_name = ".AllResConfig.datas"
TB.ALLRESCONFIG_DATAS_FIELD.number = 1
TB.ALLRESCONFIG_DATAS_FIELD.index = 0
TB.ALLRESCONFIG_DATAS_FIELD.label = 3
TB.ALLRESCONFIG_DATAS_FIELD.has_default_value = false
TB.ALLRESCONFIG_DATAS_FIELD.default_value = {}
TB.ALLRESCONFIG_DATAS_FIELD.message_type = TB.RESCONFIG
TB.ALLRESCONFIG_DATAS_FIELD.type = 11
TB.ALLRESCONFIG_DATAS_FIELD.cpp_type = 10

TB.ALLRESCONFIG.name = "AllResConfig"
TB.ALLRESCONFIG.full_name = ".AllResConfig"
TB.ALLRESCONFIG.nested_types = {}
TB.ALLRESCONFIG.enum_types = {}
TB.ALLRESCONFIG.fields = {TB.ALLRESCONFIG_DATAS_FIELD}
TB.ALLRESCONFIG.is_extendable = false
TB.ALLRESCONFIG.extensions = {}

TB.BYTESCONFIG_OFFSET_FIELD.name = "offset"
TB.BYTESCONFIG_OFFSET_FIELD.full_name = ".BytesConfig.offset"
TB.BYTESCONFIG_OFFSET_FIELD.number = 1
TB.BYTESCONFIG_OFFSET_FIELD.index = 0
TB.BYTESCONFIG_OFFSET_FIELD.label = 1
TB.BYTESCONFIG_OFFSET_FIELD.has_default_value = false
TB.BYTESCONFIG_OFFSET_FIELD.default_value = 0
TB.BYTESCONFIG_OFFSET_FIELD.type = 5
TB.BYTESCONFIG_OFFSET_FIELD.cpp_type = 1

TB.BYTESCONFIG_LENGTH_FIELD.name = "length"
TB.BYTESCONFIG_LENGTH_FIELD.full_name = ".BytesConfig.length"
TB.BYTESCONFIG_LENGTH_FIELD.number = 2
TB.BYTESCONFIG_LENGTH_FIELD.index = 1
TB.BYTESCONFIG_LENGTH_FIELD.label = 1
TB.BYTESCONFIG_LENGTH_FIELD.has_default_value = false
TB.BYTESCONFIG_LENGTH_FIELD.default_value = 0
TB.BYTESCONFIG_LENGTH_FIELD.type = 5
TB.BYTESCONFIG_LENGTH_FIELD.cpp_type = 1

TB.BYTESCONFIG_NAME_FIELD.name = "name"
TB.BYTESCONFIG_NAME_FIELD.full_name = ".BytesConfig.name"
TB.BYTESCONFIG_NAME_FIELD.number = 3
TB.BYTESCONFIG_NAME_FIELD.index = 2
TB.BYTESCONFIG_NAME_FIELD.label = 1
TB.BYTESCONFIG_NAME_FIELD.has_default_value = false
TB.BYTESCONFIG_NAME_FIELD.default_value = ""
TB.BYTESCONFIG_NAME_FIELD.type = 9
TB.BYTESCONFIG_NAME_FIELD.cpp_type = 9

TB.BYTESCONFIG.name = "BytesConfig"
TB.BYTESCONFIG.full_name = ".BytesConfig"
TB.BYTESCONFIG.nested_types = {}
TB.BYTESCONFIG.enum_types = {}
TB.BYTESCONFIG.fields = {TB.BYTESCONFIG_OFFSET_FIELD, TB.BYTESCONFIG_LENGTH_FIELD, TB.BYTESCONFIG_NAME_FIELD}
TB.BYTESCONFIG.is_extendable = false
TB.BYTESCONFIG.extensions = {}

TB.ALLBYTESCONFIG_DATAS_FIELD.name = "datas"
TB.ALLBYTESCONFIG_DATAS_FIELD.full_name = ".AllBytesConfig.datas"
TB.ALLBYTESCONFIG_DATAS_FIELD.number = 1
TB.ALLBYTESCONFIG_DATAS_FIELD.index = 0
TB.ALLBYTESCONFIG_DATAS_FIELD.label = 3
TB.ALLBYTESCONFIG_DATAS_FIELD.has_default_value = false
TB.ALLBYTESCONFIG_DATAS_FIELD.default_value = {}
TB.ALLBYTESCONFIG_DATAS_FIELD.message_type = TB.BYTESCONFIG
TB.ALLBYTESCONFIG_DATAS_FIELD.type = 11
TB.ALLBYTESCONFIG_DATAS_FIELD.cpp_type = 10

TB.ALLBYTESCONFIG.name = "AllBytesConfig"
TB.ALLBYTESCONFIG.full_name = ".AllBytesConfig"
TB.ALLBYTESCONFIG.nested_types = {}
TB.ALLBYTESCONFIG.enum_types = {}
TB.ALLBYTESCONFIG.fields = {TB.ALLBYTESCONFIG_DATAS_FIELD}
TB.ALLBYTESCONFIG.is_extendable = false
TB.ALLBYTESCONFIG.extensions = {}


AllBytesConfig = protobuf.Message(TB.ALLBYTESCONFIG)
AllResConfig = protobuf.Message(TB.ALLRESCONFIG)
BytesConfig = protobuf.Message(TB.BYTESCONFIG)
ResConfig = protobuf.Message(TB.RESCONFIG)

