-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('Shape_pb',package.seeall)

local TB = {}

TB.SHAPEDATA = protobuf.Descriptor();
TB.SHAPEDATA_ID_FIELD = protobuf.FieldDescriptor();
TB.SHAPEDATA_NPCID_FIELD = protobuf.FieldDescriptor();
TB.SHAPEDATA_CANCANCEL_FIELD = protobuf.FieldDescriptor();
TB.ALLSHAPEDATA = protobuf.Descriptor();
TB.ALLSHAPEDATA_DATAS_FIELD = protobuf.FieldDescriptor();

TB.SHAPEDATA_ID_FIELD.name = "id"
TB.SHAPEDATA_ID_FIELD.full_name = ".ShapeData.id"
TB.SHAPEDATA_ID_FIELD.number = 1
TB.SHAPEDATA_ID_FIELD.index = 0
TB.SHAPEDATA_ID_FIELD.label = 1
TB.SHAPEDATA_ID_FIELD.has_default_value = false
TB.SHAPEDATA_ID_FIELD.default_value = 0
TB.SHAPEDATA_ID_FIELD.type = 5
TB.SHAPEDATA_ID_FIELD.cpp_type = 1

TB.SHAPEDATA_NPCID_FIELD.name = "npcID"
TB.SHAPEDATA_NPCID_FIELD.full_name = ".ShapeData.npcID"
TB.SHAPEDATA_NPCID_FIELD.number = 2
TB.SHAPEDATA_NPCID_FIELD.index = 1
TB.SHAPEDATA_NPCID_FIELD.label = 1
TB.SHAPEDATA_NPCID_FIELD.has_default_value = false
TB.SHAPEDATA_NPCID_FIELD.default_value = 0
TB.SHAPEDATA_NPCID_FIELD.type = 5
TB.SHAPEDATA_NPCID_FIELD.cpp_type = 1

TB.SHAPEDATA_CANCANCEL_FIELD.name = "canCancel"
TB.SHAPEDATA_CANCANCEL_FIELD.full_name = ".ShapeData.canCancel"
TB.SHAPEDATA_CANCANCEL_FIELD.number = 3
TB.SHAPEDATA_CANCANCEL_FIELD.index = 2
TB.SHAPEDATA_CANCANCEL_FIELD.label = 1
TB.SHAPEDATA_CANCANCEL_FIELD.has_default_value = false
TB.SHAPEDATA_CANCANCEL_FIELD.default_value = false
TB.SHAPEDATA_CANCANCEL_FIELD.type = 8
TB.SHAPEDATA_CANCANCEL_FIELD.cpp_type = 7

TB.SHAPEDATA.name = "ShapeData"
TB.SHAPEDATA.full_name = ".ShapeData"
TB.SHAPEDATA.nested_types = {}
TB.SHAPEDATA.enum_types = {}
TB.SHAPEDATA.fields = {TB.SHAPEDATA_ID_FIELD, TB.SHAPEDATA_NPCID_FIELD, TB.SHAPEDATA_CANCANCEL_FIELD}
TB.SHAPEDATA.is_extendable = false
TB.SHAPEDATA.extensions = {}

TB.ALLSHAPEDATA_DATAS_FIELD.name = "datas"
TB.ALLSHAPEDATA_DATAS_FIELD.full_name = ".AllShapeData.datas"
TB.ALLSHAPEDATA_DATAS_FIELD.number = 1
TB.ALLSHAPEDATA_DATAS_FIELD.index = 0
TB.ALLSHAPEDATA_DATAS_FIELD.label = 3
TB.ALLSHAPEDATA_DATAS_FIELD.has_default_value = false
TB.ALLSHAPEDATA_DATAS_FIELD.default_value = {}
TB.ALLSHAPEDATA_DATAS_FIELD.message_type = TB.SHAPEDATA
TB.ALLSHAPEDATA_DATAS_FIELD.type = 11
TB.ALLSHAPEDATA_DATAS_FIELD.cpp_type = 10

TB.ALLSHAPEDATA.name = "AllShapeData"
TB.ALLSHAPEDATA.full_name = ".AllShapeData"
TB.ALLSHAPEDATA.nested_types = {}
TB.ALLSHAPEDATA.enum_types = {}
TB.ALLSHAPEDATA.fields = {TB.ALLSHAPEDATA_DATAS_FIELD}
TB.ALLSHAPEDATA.is_extendable = false
TB.ALLSHAPEDATA.extensions = {}


AllShapeData = protobuf.Message(TB.ALLSHAPEDATA)
ShapeData = protobuf.Message(TB.SHAPEDATA)

