-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
module('SignTips_pb',package.seeall)

local TB = {}

TB.DESIGNEX = protobuf.Descriptor();
TB.DESIGNEX_DESIGN_FIELD = protobuf.FieldDescriptor();
TB.DESIGNEX_RATE_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS = protobuf.Descriptor();
TB.SIGNTIPS_ID_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_TYPE_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_TITLE_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_CONTENT1_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_CONTENT2_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_CONTENT3_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_CONTENT4_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_DRAWRATE_FIELD = protobuf.FieldDescriptor();
TB.SIGNTIPS_LIST_FIELD = protobuf.FieldDescriptor();
TB.ALLSIGNTIPS = protobuf.Descriptor();
TB.ALLSIGNTIPS_TIPS_FIELD = protobuf.FieldDescriptor();

TB.DESIGNEX_DESIGN_FIELD.name = "design"
TB.DESIGNEX_DESIGN_FIELD.full_name = ".designex.design"
TB.DESIGNEX_DESIGN_FIELD.number = 1
TB.DESIGNEX_DESIGN_FIELD.index = 0
TB.DESIGNEX_DESIGN_FIELD.label = 1
TB.DESIGNEX_DESIGN_FIELD.has_default_value = false
TB.DESIGNEX_DESIGN_FIELD.default_value = ""
TB.DESIGNEX_DESIGN_FIELD.type = 9
TB.DESIGNEX_DESIGN_FIELD.cpp_type = 9

TB.DESIGNEX_RATE_FIELD.name = "rate"
TB.DESIGNEX_RATE_FIELD.full_name = ".designex.rate"
TB.DESIGNEX_RATE_FIELD.number = 2
TB.DESIGNEX_RATE_FIELD.index = 1
TB.DESIGNEX_RATE_FIELD.label = 1
TB.DESIGNEX_RATE_FIELD.has_default_value = false
TB.DESIGNEX_RATE_FIELD.default_value = 0
TB.DESIGNEX_RATE_FIELD.type = 5
TB.DESIGNEX_RATE_FIELD.cpp_type = 1

TB.DESIGNEX.name = "designex"
TB.DESIGNEX.full_name = ".designex"
TB.DESIGNEX.nested_types = {}
TB.DESIGNEX.enum_types = {}
TB.DESIGNEX.fields = {TB.DESIGNEX_DESIGN_FIELD, TB.DESIGNEX_RATE_FIELD}
TB.DESIGNEX.is_extendable = false
TB.DESIGNEX.extensions = {}

TB.SIGNTIPS_ID_FIELD.name = "id"
TB.SIGNTIPS_ID_FIELD.full_name = ".SignTips.id"
TB.SIGNTIPS_ID_FIELD.number = 1
TB.SIGNTIPS_ID_FIELD.index = 0
TB.SIGNTIPS_ID_FIELD.label = 1
TB.SIGNTIPS_ID_FIELD.has_default_value = false
TB.SIGNTIPS_ID_FIELD.default_value = 0
TB.SIGNTIPS_ID_FIELD.type = 5
TB.SIGNTIPS_ID_FIELD.cpp_type = 1

TB.SIGNTIPS_TYPE_FIELD.name = "type"
TB.SIGNTIPS_TYPE_FIELD.full_name = ".SignTips.type"
TB.SIGNTIPS_TYPE_FIELD.number = 2
TB.SIGNTIPS_TYPE_FIELD.index = 1
TB.SIGNTIPS_TYPE_FIELD.label = 1
TB.SIGNTIPS_TYPE_FIELD.has_default_value = false
TB.SIGNTIPS_TYPE_FIELD.default_value = 0
TB.SIGNTIPS_TYPE_FIELD.type = 5
TB.SIGNTIPS_TYPE_FIELD.cpp_type = 1

TB.SIGNTIPS_TITLE_FIELD.name = "title"
TB.SIGNTIPS_TITLE_FIELD.full_name = ".SignTips.title"
TB.SIGNTIPS_TITLE_FIELD.number = 3
TB.SIGNTIPS_TITLE_FIELD.index = 2
TB.SIGNTIPS_TITLE_FIELD.label = 1
TB.SIGNTIPS_TITLE_FIELD.has_default_value = false
TB.SIGNTIPS_TITLE_FIELD.default_value = ""
TB.SIGNTIPS_TITLE_FIELD.type = 9
TB.SIGNTIPS_TITLE_FIELD.cpp_type = 9

TB.SIGNTIPS_CONTENT1_FIELD.name = "content1"
TB.SIGNTIPS_CONTENT1_FIELD.full_name = ".SignTips.content1"
TB.SIGNTIPS_CONTENT1_FIELD.number = 4
TB.SIGNTIPS_CONTENT1_FIELD.index = 3
TB.SIGNTIPS_CONTENT1_FIELD.label = 1
TB.SIGNTIPS_CONTENT1_FIELD.has_default_value = false
TB.SIGNTIPS_CONTENT1_FIELD.default_value = ""
TB.SIGNTIPS_CONTENT1_FIELD.type = 9
TB.SIGNTIPS_CONTENT1_FIELD.cpp_type = 9

TB.SIGNTIPS_CONTENT2_FIELD.name = "content2"
TB.SIGNTIPS_CONTENT2_FIELD.full_name = ".SignTips.content2"
TB.SIGNTIPS_CONTENT2_FIELD.number = 5
TB.SIGNTIPS_CONTENT2_FIELD.index = 4
TB.SIGNTIPS_CONTENT2_FIELD.label = 1
TB.SIGNTIPS_CONTENT2_FIELD.has_default_value = false
TB.SIGNTIPS_CONTENT2_FIELD.default_value = ""
TB.SIGNTIPS_CONTENT2_FIELD.type = 9
TB.SIGNTIPS_CONTENT2_FIELD.cpp_type = 9

TB.SIGNTIPS_CONTENT3_FIELD.name = "content3"
TB.SIGNTIPS_CONTENT3_FIELD.full_name = ".SignTips.content3"
TB.SIGNTIPS_CONTENT3_FIELD.number = 6
TB.SIGNTIPS_CONTENT3_FIELD.index = 5
TB.SIGNTIPS_CONTENT3_FIELD.label = 1
TB.SIGNTIPS_CONTENT3_FIELD.has_default_value = false
TB.SIGNTIPS_CONTENT3_FIELD.default_value = ""
TB.SIGNTIPS_CONTENT3_FIELD.type = 9
TB.SIGNTIPS_CONTENT3_FIELD.cpp_type = 9

TB.SIGNTIPS_CONTENT4_FIELD.name = "content4"
TB.SIGNTIPS_CONTENT4_FIELD.full_name = ".SignTips.content4"
TB.SIGNTIPS_CONTENT4_FIELD.number = 7
TB.SIGNTIPS_CONTENT4_FIELD.index = 6
TB.SIGNTIPS_CONTENT4_FIELD.label = 1
TB.SIGNTIPS_CONTENT4_FIELD.has_default_value = false
TB.SIGNTIPS_CONTENT4_FIELD.default_value = ""
TB.SIGNTIPS_CONTENT4_FIELD.type = 9
TB.SIGNTIPS_CONTENT4_FIELD.cpp_type = 9

TB.SIGNTIPS_DRAWRATE_FIELD.name = "drawRate"
TB.SIGNTIPS_DRAWRATE_FIELD.full_name = ".SignTips.drawRate"
TB.SIGNTIPS_DRAWRATE_FIELD.number = 8
TB.SIGNTIPS_DRAWRATE_FIELD.index = 7
TB.SIGNTIPS_DRAWRATE_FIELD.label = 1
TB.SIGNTIPS_DRAWRATE_FIELD.has_default_value = false
TB.SIGNTIPS_DRAWRATE_FIELD.default_value = 0
TB.SIGNTIPS_DRAWRATE_FIELD.type = 5
TB.SIGNTIPS_DRAWRATE_FIELD.cpp_type = 1

TB.SIGNTIPS_LIST_FIELD.name = "list"
TB.SIGNTIPS_LIST_FIELD.full_name = ".SignTips.list"
TB.SIGNTIPS_LIST_FIELD.number = 9
TB.SIGNTIPS_LIST_FIELD.index = 8
TB.SIGNTIPS_LIST_FIELD.label = 3
TB.SIGNTIPS_LIST_FIELD.has_default_value = false
TB.SIGNTIPS_LIST_FIELD.default_value = {}
TB.SIGNTIPS_LIST_FIELD.message_type = TB.DESIGNEX
TB.SIGNTIPS_LIST_FIELD.type = 11
TB.SIGNTIPS_LIST_FIELD.cpp_type = 10

TB.SIGNTIPS.name = "SignTips"
TB.SIGNTIPS.full_name = ".SignTips"
TB.SIGNTIPS.nested_types = {}
TB.SIGNTIPS.enum_types = {}
TB.SIGNTIPS.fields = {TB.SIGNTIPS_ID_FIELD, TB.SIGNTIPS_TYPE_FIELD, TB.SIGNTIPS_TITLE_FIELD, TB.SIGNTIPS_CONTENT1_FIELD, TB.SIGNTIPS_CONTENT2_FIELD, TB.SIGNTIPS_CONTENT3_FIELD, TB.SIGNTIPS_CONTENT4_FIELD, TB.SIGNTIPS_DRAWRATE_FIELD, TB.SIGNTIPS_LIST_FIELD}
TB.SIGNTIPS.is_extendable = false
TB.SIGNTIPS.extensions = {}

TB.ALLSIGNTIPS_TIPS_FIELD.name = "tips"
TB.ALLSIGNTIPS_TIPS_FIELD.full_name = ".AllSignTips.tips"
TB.ALLSIGNTIPS_TIPS_FIELD.number = 1
TB.ALLSIGNTIPS_TIPS_FIELD.index = 0
TB.ALLSIGNTIPS_TIPS_FIELD.label = 3
TB.ALLSIGNTIPS_TIPS_FIELD.has_default_value = false
TB.ALLSIGNTIPS_TIPS_FIELD.default_value = {}
TB.ALLSIGNTIPS_TIPS_FIELD.message_type = TB.SIGNTIPS
TB.ALLSIGNTIPS_TIPS_FIELD.type = 11
TB.ALLSIGNTIPS_TIPS_FIELD.cpp_type = 10

TB.ALLSIGNTIPS.name = "AllSignTips"
TB.ALLSIGNTIPS.full_name = ".AllSignTips"
TB.ALLSIGNTIPS.nested_types = {}
TB.ALLSIGNTIPS.enum_types = {}
TB.ALLSIGNTIPS.fields = {TB.ALLSIGNTIPS_TIPS_FIELD}
TB.ALLSIGNTIPS.is_extendable = false
TB.ALLSIGNTIPS.extensions = {}


AllSignTips = protobuf.Message(TB.ALLSIGNTIPS)
SignTips = protobuf.Message(TB.SIGNTIPS)
designex = protobuf.Message(TB.DESIGNEX)

