module("EventDefine_Social", package.seeall)

local GEN_GROUP = GameEvent.GEN_GROUP;
local GEN_EVENT = GameEvent.GEN_EVENT;

function InitEvent()

	--好友
	GEN_GROUP("FRIEND")
	GEN_EVENT("FRIEND_BASIC_INFO")--好友基本信息:备注
	GEN_EVENT("FRIEND_REGROUP_INFO")--分组的基本信息
	GEN_EVENT("FRIEND_REGROUP_MEMBERCOUNT")--分组的成员数量变化信息
	GEN_EVENT("FRIEND_REGROUP_COUNT")--分组数量变化
	GEN_EVENT("FRIEND_SYNC_ALL_RELATION")--所有成员信息
	GEN_EVENT("FRIEND_REGROUP_BLACKLIST")--黑名单变化
	GEN_EVENT("FRIEND_RELATION_CHANGE");--好友关系变化
	GEN_EVENT("FRIEND_DELETE_FRIEND");--解除好友关系

	GEN_EVENT("FAST_CHAT_CHANGE"); -- 快速聊天设置变化

	
	GEN_EVENT("FRIEND_ONLINE_NOTIFY")--好友上线通知
	GEN_EVENT("FRIEND_APPLICATION_NOTIFY")--好友申请通知

	GEN_EVENT("FRIEND_ACTIVE_ADD")--添加常用联系人
	GEN_EVENT("FRIEND_ACTIVE_DELETE")--删除常用联系人
	
	--好友群
	GEN_GROUP("FRIENDQUN")
	GEN_EVENT("FRIENDQUN_NEW_QUN");--新建群
	GEN_EVENT("FRIENDQUN_REMOVE_QUN");--群销毁或者退出
	GEN_EVENT("FRIENDQUN_MEMBER_ADD");--群成员变动
	GEN_EVENT("FRIENDQUN_MEMBER_DELETE");--群成员变动
	GEN_EVENT("FRIENDQUN_MSGRECORD_ADD");--历史消息变动
	GEN_EVENT("FRIENDQUN_BASIC_INFO");--群基本消息变动
	GEN_EVENT("FRIENDQUN_ADMIN");--管理员变动
	GEN_EVENT("FRIENDQUN_APPLY_INIT");--申请列表更新完成
	GEN_EVENT("FRIENDQUN_APPLY_ADD");--新添申请者
	GEN_EVENT("FRIENDQUN_APPLY_REMOVE");--移除申请者
	
	--好友聊天
	GEN_GROUP("FRIENDCHAT")
	GEN_EVENT("FRIENDCHAT_NEW_ITEM");--更新聊天对象列表
	GEN_EVENT("FRIENDCHAT_NEW_MESSAGE");--更新聊天内容
	GEN_EVENT("FRIENDCHAT_CLEAR_MESSAGE");--清空聊天记录
	
	
	--好友申请
	GEN_GROUP("FRIENDASK")
	GEN_EVENT("FRIENDASK_INIT_INFO");--更新好友申请列表
	GEN_EVENT("FRIENDASK_NEW_APPLIER");--更新好友申请列表
	GEN_EVENT("FRIENDASK_ITEM_PROCESSED");--更新好友申请列表
	GEN_EVENT("FRIENDASK_BATCH_PROCESSED");--更新好友申请列表
	
	--好友推荐
	GEN_GROUP("FRIENDRECOMMEND")
	GEN_EVENT("FRIENDRECOMMEND_HEAD_COUNT");--更新已读数量
	GEN_EVENT("FRIENDRECOMMEND_PLAYER_CHANGE");--更新推荐信息
	GEN_EVENT("FRIENDRECOMMEND_SEARCH_RESULT");--搜索结果
	GEN_EVENT("FRIENDRECOMMEND_GET_SETTINGS");--获得推荐设置
	GEN_EVENT("FRIENDRECOMMEND_SETTINGS_CHANGE");--修改了推荐设置；
	GEN_EVENT("FRIENDRECOMMEND_DELETE_ITEM");--删除推荐项
	
	--社交SocialPlayer的信息
	GEN_GROUP("SOCIAL")
	GEN_EVENT("ALL_PLAYERS_FRIEND_ATTRS"); --所有玩家的friend属性更新
	GEN_EVENT("ALL_PLAYERS_VOLATILE_ATTRS"); --所有玩家的volatile属性更新
	GEN_EVENT("SOCIAL_ATTRIBUTE"); -- one's any 属性更新
	GEN_EVENT("SOCIAL_FRIEND_ATTR"); -- one's friend 属性更新
	GEN_EVENT("SOCIAL_NORMAL_ATTR"); -- one's normal 属性更新
	GEN_EVENT("SOCIAL_PHOTO_ATTR"); -- one's photo 属性更新
	GEN_EVENT("SOCIAL_PRIVATE_ATTR"); -- one's private 属性更新;
	GEN_EVENT("SOCIAL_USERDEFINE_ATTR"); -- one's userdefine 属性更新;
	GEN_EVENT("SOCIAL_VOLATILE_ATTR"); -- one's volatile 属性更新;
	GEN_EVENT("ON_OFF_LINE"); --在线离线；

	GEN_EVENT("PLAYER_UNREQUITED_LOVER");--暗恋
	GEN_EVENT("PLAYER_REMARK");--暗恋
	
	--玩家SocialSelf在社交服的属性
	GEN_GROUP("SOCIAL_SELF")
	GEN_EVENT("PLAYER_ICON_INDEX");--社交头像Index
	GEN_EVENT("PLAYER_SELF_INTRO");--自我介绍
	GEN_EVENT("PLAYER_VOICEURL");--VOICE URL
	GEN_EVENT("PLAYER_VOICELENGTH");--VOICE LENGTH
	GEN_EVENT("PLAYER_HOME");--家乡
	GEN_EVENT("PLAYER_LOCATION");--地址

	GEN_EVENT("PLAYER_PHOTO_ADD"); --添加照片
	GEN_EVENT("PLAYER_PHOTO_DEL"); --删除照片

	GEN_EVENT("PLAYER_BIRTHDAY");--生日
	GEN_EVENT("PLAYER_GENDER");--社交性别
	GEN_EVENT("PLAYER_STAR");--星座

	--好友送礼
	GEN_GROUP("GIFT")
	GEN_EVENT("GIFT_CLOSE_UI_SYSTEM");--关闭UI
	GEN_EVENT("GIFT_CLOSE_MAIN_UI");--关闭SendMain
	GEN_EVENT("GIFT_SEND_SUCCESS");--送礼成功
	GEN_EVENT("GIFT_SEND_RECORD_CHANGE");--送礼记录变化
	GEN_EVENT("GIFT_RECEIVE_RECORD_CHANGE");--收礼记录变化
	
	
end

return EventDefine_Social;